name: Bonjour
on:
  pull_request:
    branches:
      - main
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    env:
      IMAGE_NAME: "mynode"
    steps:
      - uses: actions/checkout@v4

      # Lint du Dockerfile
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./Dockerfile

      # Construction de l’image Docker
      - run: docker image build --tag="${IMAGE_NAME}" ./

      # Lint du code source
      - run: docker container run "${IMAGE_NAME}" npm run lint

      # Exécution des tests
      - run: docker container run "${IMAGE_NAME}" npm test
      
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "moha210"
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        if: startsWith(github.ref, 'refs/tags/')
        with:
          push: true
          context: "./"
          tags: moha210/sayhello:${{ github.ref_name }}
      -
        name: Build and push If Main UNSTABLE
        uses: docker/build-push-action@v6
        if: github.ref == 'refs/heads/main'
        with:
          push: true
          context: "./"
          tags: moha210/sayhello:unstable